USE [HEMM]
GO

/****** Object:  StoredProcedure [dbo].[CDM_REPORT]    Script Date: 6/6/2017 10:39:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[CDM_REPORT]

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

create table #LIMC(ITEM_NO varchar(255),	ITEM_DESC varchar(255),	UM_CD varchar(255),	MFR_NAME varchar(255),	
					PRICE varchar(255),	SLOC_STAT varchar(255),	VEND_NAME varchar(255),	VEND_CTLG_NO varchar(255),	
					PAT_CHRG_NO varchar(255),	PAT_CHRG_PRICE varchar(255),	LOC_NAME varchar(255))
INSERT INTO #LIMC 
	EXEC CDM_LocItemMastCat '(1000)','(2366,2365,1002,1001,2254,2150,2001)','Y','(''1'',''2'')',0

create table #IMC(ITEM_NO varchar(255),	ITEM_DESCR varchar(255),	NAME varchar(255),	VEND_ID varchar(255),	
VEND_CTLG_NO varchar(255),	MFR_CTLG_NO varchar(255),	MFR_NAME varchar(255),	MFR_ID varchar(255),	
ORDER_UM_CD varchar(255),	UM_CD1 varchar(255),	TO_QTY1 varchar(255),	UM_CD2 varchar(255),	TO_QTY2 varchar(255),
UM_CD3 varchar(255))
INSERT INTO #IMC 				
	EXEC CDM_ItemMastCat '(1000)','N','%','(1,2)',0
	

CREATE TABLE #CDM_MFR (MFR_ID INT,MFR_NAME VARCHAR(40), MFR_NO VARCHAR(8))
INSERT INTO #CDM_MFR
	SELECT MFR_ID,NAME, MFR_NO FROM MFR ORDER BY MFR_ID
	
	
CREATE TABLE #CDM_VEND (VEND_ID INT,VEND_CODE VARCHAR(20),NAME VARCHAR(40))
INSERT INTO #CDM_VEND
	SELECT VEND_ID, VEND_CODE, NAME FROM VEND ORDER BY VEND_ID

   
SELECT #LIMC.PAT_CHRG_NO, 
#LIMC.PAT_CHRG_NO, 
#LIMC.ITEM_NO, 
#LIMC.ITEM_DESC, 
#LIMC.PAT_CHRG_NO, 
#LIMC.VEND_NAME, 
#CDM_VEND.VEND_CODE, 
#LIMC.VEND_CTLG_NO, 
MFR_NO,
#CDM_MFR.MFR_NAME, 
#IMC.MFR_CTLG_NO, 
#IMC.ORDER_UM_CD, 
#IMC.UM_CD3, 
#IMC.TO_QTY2, 
#IMC.UM_CD2, 
#IMC.TO_QTY1, 
#IMC.UM_CD1, 
#LIMC.UM_CD, 
#LIMC.PRICE, 
#LIMC.PAT_CHRG_PRICE,
#LIMC.LOC_NAME
FROM ((#LIMC LEFT JOIN #IMC ON #LIMC.ITEM_NO = #IMC.ITEM_NO) INNER JOIN #CDM_MFR ON #LIMC.MFR_NAME = #CDM_MFR.MFR_NAME) 
INNER JOIN #CDM_VEND ON #LIMC.VEND_NAME = #CDM_VEND.NAME;

   
END

GO


